#!/bin/bash

#-------------------------------------------------------------------------------
# Shell script to automate passwordless ssh access between two nodes. 
# Author: Ninad Sathaye
# Initial commit: Nov 12, 2016
# See Also: CfC_ppc_installer.sh (the caller)
#-------------------------------------------------------------------------------

m_ip=$1
w_ip=$2
root_pw=$3
#ssh_opts=$4
#ssh_opts='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
ssh_opts=''

# ------------------------------------------------------------------------------
# To avoid clutter, create a new variable to represent password-provided scp 
# and ssh with some optional args.
# TODO: shell doesn't seem to like the string. Perhaps echo it? Disabling it.
# ------------------------------------------------------------------------------
##SCP_CMD="sshpass -p$root_pw scp $ssh_opts"
##SSH_CMD="sshpass -p$root_pw ssh -t $ssh_opts"
##SSH_COPY_ID_CMD="sshpass -p$root_pw  ssh-copy-id $ssh_opts"

# If it is key based authentication
#SSH_CMD="ssh -i power-cfc.pem -t $ssh_opts ubuntu@$m_ip "printf \"$root_pw\n$root_pw\n$root_pw\n\" | sudo -S passwd root"

echo "In setup_passwordless_ssh, m_ip=$m_ip, w_ip=$w_ip root_pw=$root_pw"

echo "[1] Enable root login (ssh root@ip) for the VMs ----------------------"

echo "Setting the root password for the master node: $m_ip ..."
sshpass -p$root_pw ssh -t $ssh_opts ubuntu@$m_ip "printf \"$root_pw\n$root_pw\n$root_pw\n\" | sudo -S passwd root"

echo "Setting the root password for the worker node: $w_ip ..."
sshpass -p$root_pw ssh -t $ssh_opts ubuntu@$w_ip "printf \"$root_pw\n$root_pw\n$root_pw\n\" | sudo -S passwd root"

echo "Done setting the root passwords."

echo "Updating sshd_config for master node: $m_ip ..."

set -x

# ------------------------------------------------------------------------------
# Enable root login (ssh root@ip) for the VM
# In /etc/ssh/sshd_config , change "PermitRootLogin no" to "PermitRootLogin yes"
# sed -i 's/original/new/g' file.txt   
# 'g' is for global (replace call). Ignore that option.
# ------------------------------------------------------------------------------
echo $root_pw | sudo -S sed -i 's/PermitRootLogin no/PermitRootLogin yes/' /etc/ssh/sshd_config
echo $root_pw | sudo -S sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

#-------------------------------------------------------------------------------
# Important restart sshd service. 
#-------------------------------------------------------------------------------
echo $root_pw | sudo -S service sshd restart 

# Need to run similar steps for the worker node 
#sshpass -p$root_pw ssh -t ubuntu@$w_ip "sudo sed -i 's/PermitRootLogin no/PermitRootLogin yes/' /etc/ssh/sshd_config"


echo "Updating sshd_config for the worker node: $w_ip"

sshpass -p$root_pw ssh -t $ssh_opts ubuntu@$w_ip "echo $root_pw | sudo -S sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config"
sshpass -p$root_pw ssh -t $ssh_opts ubuntu@$w_ip "echo $root_pw | sudo -S service sshd restart"

set +x
echo "[2] Enabling password-less ssh: Generating public-private key pair"

set -x

##printf "\n\n\n" | ssh-keygen -t rsa

keys_dir=".ssh"
mkdir -p ~/$keys_dir
ssh-keygen -t rsa -f ~/$keys_dir/ssh_key -P ''
sshpass -p$root_pw  ssh-copy-id $ssh_opts -i ~/$keys_dir/ssh_key root@$m_ip

# TODO: Need to enable ssh root@worker node access first! Not working. 
sshpass -p$root_pw  ssh-copy-id $ssh_opts -i ~/$keys_dir/ssh_key root@$w_ip

ls ~/$keys_dir/ssh_key

# Make sure to change the permission to 400
chmod 400 ~/$keys_dir/ssh_key

# Copy the ssh key to the master node. TODO: will it preserve 400 access? Check.
sshpass -p$root_pw scp $ssh_opts ~/$keys_dir/ssh_key root@$m_ip:/home/ubuntu/

# Needed on Worker?
sshpass -p$root_pw scp $ssh_opts ~/$keys_dir/ssh_key root@$w_ip:/home/ubuntu/


echo "End of setup_passwordless_ssh"
echo "Now, from master node (as a root) you can run ssh -i ~/.ssh/ssh_key root@ip for passwordless access."
